### PR TITLE
Remove messageId from logs

### PR DESCRIPTION
**Pull request by treygriffith**
This change removes `messageId` from the logs, instead relying on the constructor to stub the logger if there is a need to put special messaging in.

### CODE REVIEW

**Comment by treygriffith** [comment]
This is a breaking change, so all dependent repos need to have updated usage before merging.

**Comment by dannypaz** [comment]
@treygriffith love the change. make sure to cut a release after merging.

**Review by dannypaz — APPROVED** [review]
LGTM

**Comment by treygriffith** [comment]
Closing this as outdated.

**Pull request closed without merging**
